freebsd_instance:
  image: freebsd-13-1-release-amd64

env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[5658d2d703118b074accb59d28381d46e41ab09651434f8b85c64951b69d49c966a83f3206123070f56ab78f6fc84aef]
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  auto_cancellation: false
  stateful: false
  setup_script:
    - pkg install -y curl wget zip pkgconf cmake qt5-qmake qt5-widgets qt5-buildtools kf5-kwindowsystem qt5-testlib
  test_script:
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j$(sysctl -n hw.ncpu)
    - zip --symlinks -r launch_FreeBSD.zip launch open bundle-thumbnailer
    - case "$CIRRUS_BRANCH" in *pull/*) echo "Skipping since it's a pull request" ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; fetch https://github.com/probonopd/continuous-release-manager/releases/download/continuous/continuous-release-manager-freebsd && chmod +x continuous-release-manager-freebsd && ./continuous-release-manager-freebsd && ./ghr -replace -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
