name: Build for Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_ubuntu:
    runs-on: ubuntu-22.04 # TODO: Make build on 20.04 Qt 5.12

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies for Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl wget zip cmake pkgconf libqt5widgets5 qttools5-dev libkf5windowsystem-dev

      - name: Build and package for Ubuntu
        run: |
          git submodule update --init --recursive
          mkdir build ; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          make DESTDIR=out install
          find out/
          cd out/ && zip --symlinks -r ../launch_Ubuntu.zip . && cd -

      - name: Upload Ubuntu artifact
        uses: actions/upload-artifact@v2
        with:
          name: launch-artifact-ubuntu
          path: build/launch_Ubuntu.zip
          
      - name: Create GitHub Release using Continuous Release Manager
        if: github.event_name == 'push'  # Only run for push events, not pull requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              curl -L -o continuous-release-manager-linux https://github.com/probonopd/continuous-release-manager/releases/download/continuous/continuous-release-manager-linux
              chmod +x continuous-release-manager-linux
              ./continuous-release-manager-linux
              RELEASE_ID=$(./continuous-release-manager-linux)
              echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV

      - name: Upload to GitHub Release
        if: github.event_name == 'push'  # Only run for push events, not pull requests
        uses: xresloader/upload-to-github-release@v1.3.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/*zip"
          draft: false
          verbose: true
          branches: main
          tag_name: continuous
          release_id: ${{ env.RELEASE_ID }}
